package com.example.quickcash.map;

import android.content.Intent;
import android.os.Bundle;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.fragment.app.FragmentActivity;

import com.example.quickcash.R;
import com.example.quickcash.core.AppConstants;
import com.example.quickcash.databinding.ActivityMapsBinding;
import com.google.android.gms.maps.CameraUpdateFactory;
import com.google.android.gms.maps.GoogleMap;
import com.google.android.gms.maps.OnMapReadyCallback;
import com.google.android.gms.maps.SupportMapFragment;
import com.google.android.gms.maps.model.LatLng;
import com.google.android.gms.maps.model.Marker;
import com.google.android.gms.maps.model.MarkerOptions;

/**
 * A majority of this code was generated by the IDE itself, mainly the setup and the onCreate method.
 * The rest of the code was adapted by Jay, and the marker functionality was mostly Matthew.
 */

public class MapsActivity extends FragmentActivity implements OnMapReadyCallback {

    private GoogleMap mMap;
    private String city; //will remove if its ends up being unused
    private ActivityMapsBinding binding;
    final static LatLng halifax = new LatLng(44.6389821,-63.5932006);
    final static LatLng dartmouth = new LatLng(44.6856602,-63.5642182);
    final static LatLng bedford = new LatLng(44.7264114,-63.7090165);

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        binding = ActivityMapsBinding.inflate(getLayoutInflater());
        setContentView(binding.getRoot());
        city = getCity();

        // Obtain the SupportMapFragment and get notified when the map is ready to be used.
        SupportMapFragment mapFragment = (SupportMapFragment) getSupportFragmentManager()
                .findFragmentById(R.id.map);
        assert mapFragment != null; //precautionary
        mapFragment.getMapAsync(this);
    }

    protected String getCity(){
        Intent mapIntent = getIntent();
        return mapIntent.getStringExtra("jobLocation");
    }

    protected String getJobTitle(){
        Intent mapIntent = getIntent();
        return mapIntent.getStringExtra("jobTitle");
    }

    protected String getJobSalary(){
        Intent mapIntent = getIntent();
        return mapIntent.getStringExtra("jobSalary");
    }

    protected LatLng getLocation() {
        switch (city) {
            case AppConstants.HALIFAX:
                return halifax;
            case AppConstants.DARTMOUTH:
                return dartmouth;
            case AppConstants.BEDFORD:
                return bedford;
        }
        return null;
    }

    @Override
    public void onMapReady(@NonNull GoogleMap googleMap) {
        mMap = googleMap;

        LatLng location = getLocation();

        mMap.addMarker(new MarkerOptions().position(location).title(getJobTitle()).snippet("Salary: " + getJobSalary()));

        mMap.moveCamera(CameraUpdateFactory.newLatLngZoom(location,AppConstants.MAP_NORMAL_ZOOM));

        mMap.setOnMarkerClickListener(new GoogleMap.OnMarkerClickListener() {
            @Override
            public boolean onMarkerClick(@NonNull Marker marker) {
                marker.showInfoWindow();
                return false;
            }
        });
    }
}